### ISSUE TITLE
How can I use Panko::Response with a single object?

### ISSUE THREAD

**Issue by dkulchenko** [panko-serializer/panko_serializer#33]
The example uses an ArraySerializer as a sample use of Panko::Response, but I couldn't figure out how to use the same for a single item. Right now, I have:

```ruby
render json: Panko::Response.new(
      status: 'active',
      user: Panko::JsonValue.from(UserSerializer.new.serialize_to_json(user))
)
```

which works, but feels like I'm doing something wrong. Is there a better/cleaner way?

**Comment by yosiat** [comment]
Hi @dkulchenko ,

Sorry for late response, the proper solution is to break Panko's API, so instead of what you wrote you could write:

```
render json: Panko::Response.new(
      status: 'active',
      user: UserSerializer.new(user)
)
```

This is something I am planning for a later version (probably 1.*), but not for now.

The current solution will be to use new Panko API (which I will add public documentation soon) is that response creator API.

```ruby
render(
  json: Panko::Response.create do |r|
    {
      status: 'active',
      user: r.serializer(user, UserSerializer)
    }
  end
)
```

**Comment by bbay** [comment]
hello @yosiat 

What's the current preferred solution for this?

```ruby
render(
  json: Panko::Response.create do |r|
    {
      status: 'active',
      user: r.serializer(user, UserSerializer)
    }
  end
)
```
This worked for me, but I don't see it anywhere in the docs, the first version you provided didn't work for me.

thanks!

**Comment by yosiat** [comment]
@bbay Hi!

The API I wrote above is planned for future versions of Panko, currently, it won't work - since `Panko::Serializer` constructor doesn't accept a model (in your case `user`).

I updated the docs, sorry for the inconvenience - https://github.com/panko-serializer/panko_serializer/commit/e1393482d166cca58448af0a471812f2586ba1a3.

**Comment by bbay** [comment]
thanks!

**Comment by yosiat** [comment]
@bbay closing this issue, feel free to re-open it if you want to ask more questions on this topic.

**Comment by bbay** [comment]
hello again @yosiat 
Following up from my last post where I needed serialization of a single object.
I need now to pass some options and I noticed it is not possible due to the implementation in ResponseCreator (response.rb)

wdyt about adding this change?
```ruby
   # in lib/panko/response.rb
    def self.serializer(data, serializer, options = {})
      json serializer.new(options).serialize_to_json(data)
    end
```
So I can then do something like this:
```ruby
render(
  json: Panko::Response.create do |r|
    {
      status: 'active',
      user: r.serializer(user, UserSerializer, context: {index: true})
    }
  end
)
```
